### PR TITLE
Support canary deployments for ALB event

### PR DESCRIPTION
**Pull request by samcon**
## Proposed changes

This PR adds support for ALB event type. Note that contrary to the HTTP event type (i.e. API Gateway), I needed to keep the permission on the original function and not the alias.

## Types of changes

What types of changes does your code introduce to the plugin?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] Lint and unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by davidgf** [comment]
Hey @samcon, first of all, thank you very much for your contribution! It looks good to me in general, although I'd like to ask you for a couple of additions. First, could you please add some integration tests? You'd only need to create the service configuration, the original CloudFormation template and the expected outcome. You can see examples of that in the `fixtures/` folder. Also, could you please modify the sample project (under `example/`) so it includes an ALB event? Ideally, you should also include any needed resource, so that testing it is as simple as deploying the Serverless service.

**Comment by ramgrandhi** [comment]
@samcon - I'm very curious to use this feature (ALB events support for canary plugin). Do you have an indication of when it will be merged?

**Comment by davidgf** [comment]
Hi @ramgrandhi, I would happily merge this PR, but I'm just waiting for a couple of changes that have been requested. I try to be super careful when merging PRs and don't normally do so unless I had the chance to fully test it, as this plugin modifies the event source mappings and deployment settings, and we don't really want to make mistakes in that area :sweat_smile:

**Comment by ramgrandhi** [comment]
Thats true @davidgf.

Some additional info, let me know what you think.

this morning we load-tested our ALB endpoint (with target group as lambda) alongside used the :latest release of this plugin configured serverless.yml containing ALB events and interesting facts were observed.

- for Lambdas, canary deployment happened as expected with smooth transition along with health checks kicking in

- for ALB events, we DID NOT observe any outage or disturbance during the deployment process -- and they seem to adjust happily with the canary deployment pattern.

So my question, are we doing our testing wrong ? What is  the functionality your PR is going to add (sorry i did not get a chance to review the diff you are introducing)?

Cheers!

**Comment by kevinvaningen** [comment]
It looks like this PR was closed without making it to serverless-plugin-canary-deployments. I could not find the reason.  @samcon what will happen to this PR?

**Comment by samcon** [comment]
Sorry folks, I made some changes and it automatically closed this PR. I've been a bit busy but will soon complete what's missing as per David's request and resubmit.

**Comment by fxgtt** [comment]
Is there anything I can help with to get this change merged? Really waiting for ALB support and it looks like just some minor things might be blocking it.

**Comment by hlhl040** [comment]
Hi @samcon, has this PR been resubmitted?

**Comment by yorjaggy** [comment]
Hi @samcon, is there anyway we could help you to promote this to the master branch?

**Comment by JeremieDemarchez** [comment]
Hi @samcon , is it still in your plan to add support to ALB events ?

**Pull request closed without merging**
